# Generated by Django 4.0.3 on 2022-03-29 00:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='ano_fundacao',
            field=models.CharField(db_column='ANO_FUNDAÇÂO', max_length=4, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cep',
            field=models.CharField(db_column='CEP', max_length=8, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cnpj',
            field=models.CharField(db_column='CNPJ', max_length=14, validators=[django.core.validators.MinLengthValidator(14), django.core.validators.MaxLengthValidator(14)]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='numero',
            field=models.CharField(db_column='NUMERO', max_length=4, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(db_column='TELEFONE', max_length=11, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='uf',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapa'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceara'), ('ES', 'Espirito Santo'), ('GO', 'Goias'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Para'), ('PB', 'Paraiba'), ('PR', 'Parana'), ('PE', 'Pernambuco'), ('PI', 'Piaui'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande Do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('DF', 'Distrito Federal')], db_column='UF', max_length=2),
        ),
    ]
