# Generated by Django 4.0.3 on 2022-03-22 00:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cnpj',
            field=models.CharField(db_column='CNPJ', max_length=14, validators=[django.core.validators.MaxLengthValidator(14), django.core.validators.MinLengthValidator(14)]),
        ),
    ]
