# Generated by Django 4.0.3 on 2022-03-22 00:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_perfil_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='ano_fundacao',
            field=models.CharField(db_column='ANO_FUNDAÇÂO', max_length=4, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cep',
            field=models.CharField(db_column='CEP', max_length=8, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cnpj',
            field=models.CharField(db_column='CNPJ', max_length=14, validators=[django.core.validators.MinLengthValidator(14), django.core.validators.MaxLengthValidator(14)]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='numero',
            field=models.CharField(db_column='NUMERO', max_length=4, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(db_column='TELEFONE', max_length=11, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(11)]),
        ),
    ]
